include: package:pedantic/analysis_options.yaml

linter:
  rules:
    avoid_web_libraries_in_flutter: false
    always_declare_return_types: true
    annotate_overrides: true
    camel_case_types: true
    package_names: true
    prefer_const_constructors_in_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_typing_uninitialized_variables: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true