name: example
description: Example App for 'creo_color_picker' package
version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  editors: ^0.0.10
  creo_color_picker: any
  demo_items:
    git:
      url: https://github.com/creomobile/demo_items
  combos_example:
    git:
      url: https://github.com/creomobile/combos
      path: example/


dev_dependencies:
  pedantic: ^1.8.0

dependency_overrides:
  creo_color_picker:
    path: ../


flutter:
  uses-material-design: true
